export {default as Header} from "./Header.jsx"
export {default as Home} from "./Home.jsx"
export {default as Footer} from "./Footer.jsx"
export {default as Contact} from "./Contact.jsx"
export {default as Services} from "./Services.jsx"